### ISSUE TITLE
WS_HV scripts problem

### ISSUE THREAD

**Issue by MotamedNia** [cheraaqee/IQA_Lab#1]
Hi,
I have some problem with understanding your code.
I want to know the reason of  interpolating images(lines 73->88)  and change size of images (lines 47->71).
Thank you for your consideration,

**Comment by cheraaqee** [comment]
- The theoretical justifications of "interpolating images ( _feature maps_ , more correctly,) '' are what the paper ( ``` Cheraaqee, Pooryaa, et al. "Quality assessment of screen content images in wavelet domain." IEEE Transactions on Circuits and Systems for Video Technology 32.2 (2021): 566-578. ``` ) tries to explain. For a short answer, let's suffice to say that it's an effort to simulate what happens in the primary visual pathway.
- Regarding the alteration of feature maps' dimension, i.e. the lines ```47-71```, let's keep in mind that this is not an optimized implementation and they are carried out to make the feature maps compatible for element-wise operations. (The output of the interpolator seems to be of odd dimensions, hence the 1st scale's feature maps are clipped by a row or column in the case of being even. This way they can be multiplied with the similarity maps of other scales ( as in computing the ```SimMatrix``` variable).)  
Further questions are welcome <3 .

**Comment by MotamedNia** [comment]
Thank you so much for your response
